### ISSUE TITLE
Error reading Module ID from EEPROM

### ISSUE THREAD

**Issue by tomasMiddleton** [mayaculpa/hapi#141]
> pi@raspberrypi:~/hapi/src/smart_module $ python smart_module.py 
2019-05-24 19:45:34.778381 - smartmodule.log - [*] INFO - Communicator initialized
2019-05-24 19:45:35.286370 - smartmodule.log - [!!] ERROR - Error reading Module ID from EEPROM. [Errno 121] Remote I/O error.
2019-05-24 19:45:35.286777 - smartmodule.log - [!!] ERROR - Error initializing Smart Module. local variable 'bytes_' referenced before assignment.
^CTraceback (most recent call last):
  File "smart_module.py", line 700, in <module>
    main()
  File "smart_module.py", line 693, in main
    time.sleep(0.5)

First of all, hello everyone. I love this project, I have been reading a lot of it. I really like it's modularity and the avahi integration. 

I'm having some problems running **smart_module.py**, and getting the error quotes above.

I have been trying to communicate with Tyler (Linkedin, email, contact page, join us page) with no success, so I would like to know if you have another communication channel than previous mentioned, so I thought starting here.

**Comment by ozarchie** [comment]
Probably better to try Pedro

**Comment by moritz89** [comment]
Hi Tomas, I also found this project 1-2 years ago and was also really excited about the possibilities. However, I noticed that the distributed architecture would be difficult to maintain. I spun off the ideas from Tyler and Pablo and integrated them into a [hydroponics citizen science project](https://www.instagram.com/smartdigitalgarden/). You can find the data on our [Grafana server](https://data.flowleaf.co/dashboard/db/berndbox?orgId=1) and the source code over at our [Github page](https://github.com/FlowLeaf/flow-leaf-server).

If you have any questions, contact me via [LinkedIn](https://www.linkedin.com/in/moritz-ulmer-380b49106/).

**Comment by ozarchie** [comment]
The error you are seeing is from the communication with the arduino module. The module is not returning a correct ID or it has not been initialized. Have you built and installed any arduino nodes? Look in hapi/src/dumb_module/arduino

**Comment by tomasMiddleton** [comment]
> The error you are seeing is from the communication with the arduino module. The module is not returning a correct ID or it has not been initialized. Have you built and installed any arduino nodes? Look in hapi/src/dumb_module/arduino

I do. I'm installing the one configured for platformio, right now this is the serial output:

```
ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld
Initializing WiFi network....
.......IP address: 192.168.0.140
Starting communications  ...
RTU301
Firmware v2.2

RTU301
Firmware v2.2
MAC=0x5c:0xcf:0x7f:0x0:0xd6:0x9c

RTU301
Firmware v2.2
MAC=0x5c:0xcf:0x7f:0x0:0xd6:0x9c
IP=192.168.0.140

RTU301
Firmware v2.2
MAC=0x5c:0xcf:0x7f:0x0:0xd6:0x9c
IP=192.168.0.140
Digital= 17
Analog= 1
Free SRAM: 50712k
Idle Mode: False
Setup Complete. Listening for connections.
```
 Still getting:
`pi@raspberrypi:~/hapi/src/smart_module $ python smart_module.py
2019-05-27 14:00:17.162855 - smartmodule.log - [*] INFO - Communicator initializ                                                  ed
2019-05-27 14:00:17.670594 - smartmodule.log - [!!] ERROR - Error reading Module                                                   ID from EEPROM. [Errno 121] Remote I/O error.
2019-05-27 14:00:17.670932 - smartmodule.log - [!!] ERROR - Error initializing S                                                  mart Module. local variable 'bytes_' referenced before assignment.
^CTraceback (most recent call last):
  File "smart_module.py", line 700, in <module>
    main()
  File "smart_module.py", line 693, in main
    time.sleep(0.5)
KeyboardInterrupt
`



> Hi Tomas, I also found this project 1-2 years ago and was also really excited about the possibilities. However, I noticed that the distributed architecture would be difficult to maintain. I spun off the ideas from Tyler and Pablo and integrated them into a [hydroponics citizen science project](https://www.instagram.com/smartdigitalgarden/). You can find the data on our [Grafana server](https://data.flowleaf.co/dashboard/db/berndbox?orgId=1) and the source code over at our [Github page](https://github.com/FlowLeaf/flow-leaf-server).
> 
> If you have any questions, contact me via [LinkedIn](https://www.linkedin.com/in/moritz-ulmer-380b49106/).

Thank you! Looks like a great data visualization/interpretation layer,  I will definitely try it out after I set the base HAPI system. Coincidentally, I'm also using a BME280, love it.
